export const AuthApi = {
  SIGN_IN: '/users/signIn',
  SIGN_IN_WITH_CODE: '/users/signin-withcode',
  SIGN_UP: '/users/signUp',
  ACTIVE_AUTH_CODE: '/users/active',
  GET_USER_BY_ID: '/users/getUserById/',
  CHANGE_STATUS_IS_ONLINE: '/users/changeStatusOnline',
  UPDATE_INFOR: '/users/update-infor',
  LOGIN_FB: '/users/login-fb',
  LOGIN_GG: '/users/login-gg',
  FORGOT_PW: '/users/order-reset-password',
  RESEND_ORDER_RESET_PASSWORD: '/users/resend-order-reset-password',
  RESET_PASSWORD: '/users/reset-password',
};

export const REPONSE_CONSTANT = {
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL',
  GET_USER_BY_ID_SUCCESS: 'GET_USER_BY_ID_SUCCESS',
  GET_USER_BY_ID_FAIL: 'GET_USER_BY_ID_FAIL',
  CHANGE_STATUS_IS_ONLINE_SUCCESS: 'CHANGE_STATUS_IS_ONLINE_SUCCESS',
  CHANGE_STATUS_IS_ONLINE_FAIL: 'CHANGE_STATUS_IS_ONLINE_FAIL',
  UPDATE_INFOR_SUCCESS: 'UPDATE_INFOR_SUCCESS',
  UPDATE_INFOR_FAIL: 'UPDATE_INFOR_FAIL',
  LOGIN_FB_SUCCESS: 'LOGIN_FB_SUCCESS',
  LOGIN_FB_FAIL: 'LOGIN_FB_FAIL',
  LOGIN_GG_SUCCESS: 'LOGIN_GG_SUCCESS',
  LOGIN_GG_FAIL: 'LOGIN_GG_FAIL',
  ACTIVE_AUTH_CODE_SUCCESS: 'ACTIVE_AUTH_CODE_SUCCESS',
  ACTIVE_AUTH_CODE_FAIL: 'ACTIVE_AUTH_CODE_FAIL',
  FORGOT_PW_SUCCESS: 'FORGOT_PW_SUCCESS',
  FORGOT_PW_FAIL: 'FORGOT_PW_FAIL',
  RESEND_ORDER_RESET_PASSWORD_SUCCESS: 'RESEND_ORDER_RESET_PASSWORD_SUCCESS',
  RESEND_ORDER_RESET_PASSWORD_FAIL: 'RESEND_ORDER_RESET_PASSWORD_FAIL',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAIL: 'RESET_PASSWORD_FAIL',
};

export const REPONSE_MESSAGE = {
  SIGN_IN_SUCCESS: 'Đăng nhập thành công',
  SIGN_IN_FAIL: 'Đăng nhập thất bại',
  SIGN_UP_SUCCESS: 'Đăng ký thành công',
  SIGN_UP_FAIL: 'Đăng ký thất bại',
};

export const JOIN_ROOM = 'JOIN_ROOM';
