version: '3.4'

services:
  redis:
    image: redis:latest
    container_name: ecommerce_redis
    ports:
      - '6382:6379'
    volumes:
      - .docker/data/redis:/data
    restart: always

  mysql:
    image: mysql:latest
    container_name: ecommerce_mysql
    ports:
      - '3309:3306'
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      - .docker/data/mysql:/data
    environment:
      - MYSQL_DATABASE=ECOMMERCE
      - MYSQL_ROOT_PASSWORD=12345
    command: bash -c "cp /docker-entrypoint-initdb.d/init-ecommerce.sql /docker-entrypoint-initdb.d/init-ecommerce-temp.sql && docker-entrypoint.sh --init-file /docker-entrypoint-initdb.d/init-ecommerce-temp.sql"
    restart: always

  # app:
  #   image: ecommerce:v1
  #   build: .
  #   ports:
  #     - '8000:8000'
  #   env_file: .env
  #   depends_on:
  #     - redis
  #     - mysql
  #   command: ['./scripts/wait-for-it.sh', '-t', '10', 'redis:6380', '--', 'node', 'build/server.js']
