export const ChatAppApi = {
  LIST_USER: '/users/listUser',
  SAVE_CONVERT_STATION: '/convertStations/saveConvertStation',
  GET_LIST_MESSAGE: '/messages/getListMessages',
  NEW_MESSAGE: '/messages/newMessage',
  CHANGE_STATUS_OFFLINE: '/users/changeStatusoffline',
  UPLOAD_AWS_S3: '/images/upload-aws3',
  REMOVE_IMG_AWS3: '/images/remove-img-aws3',
};

export const REPONSE_CONSTANT = {
  LIST_USER_SUCCESS: 'LIST_USER_SUCCESS',
  LIST_USER_FAIL: 'LIST_USER_FAIL',
  SAVE_CONVERT_STATION_SUCCESS: 'SAVE_CONVERT_STATION_SUCCESS',
  SAVE_CONVERT_STATION_FAIL: 'SAVE_CONVERT_STATION_FAIL',
  GET_LIST_MESSAGE_SUCCESS: 'GET_LIST_MESSAGE_SUCCESS',
  GET_LIST_MESSAGE_FAIL: 'GET_LIST_MESSAGE_FAIL',
  NEW_MESSAGE_SUCCESS: 'NEW_MESSAGE_SUCCESS',
  NEW_MESSAGE_FAIL: 'NEW_MESSAGE_FAIL',
  CHANGE_STATUS_OFFLINE_SUCCESS: 'CHANGE_STATUS_OFFLINE_SUCCESS',
  CHANGE_STATUS_OFFLINE_FAIL: 'CHANGE_STATUS_OFFLINE_FAIL',
  UPLOAD_AWS_S3_SUCCESS: 'UPLOAD_AWS_S3_SUCCESS',
  UPLOAD_AWS_S3_FAIL: 'UPLOAD_AWS_S3_FAIL',
  REMOVE_IMG_AWS3_SUCCESS: 'REMOVE_IMG_AWS3_SUCCESS',
  REMOVE_IMG_AWS3_FAIL: 'REMOVE_IMG_AWS3_FAIL',
};

export const REPONSE_MESSAGE = {
  LIST_USER_SUCCESS: 'get list successfully.',
  LIST_USER_FAIL: 'get list failed.',
  LIST_MESSAGE_SUCCESS: 'get list successfully.',
  LIST_MESSAGE_FAIL: 'get list failed.',
};
